### PR TITLE
save method

### PR DESCRIPTION
**Pull request by Ksengine**
added save feature and formatted code

### CODE REVIEW

**Review by Ksengine — COMMENTED** [review]
ok

**Comment by Ksengine** [comment]
Can you make me a maintainer of this repo

**Comment by linuxlawson** [comment]
I think I will maintain it myself.

**Comment by Ksengine** [comment]
ok.
I asked because I like to develop a  text editor.

**Comment by linuxlawson** [comment]
Yes I understand. I'm a beginner myself and am just learning as I go. You probably know enough to develop one yourself. 👍🏻 
If I can do it, I'm sure you can.

**Comment by Ksengine** [comment]
read my description,(hover my icon)

**Comment by linuxlawson** [comment]
You're 16 yrs old? Why aren't you out catching crabs??

**Comment by Ksengine** [comment]
> Why aren't you out catching crabs??

❓

**Comment by linuxlawson** [comment]
Oh never mind that, I was just joking around. Keep to the code!

**Pull request merged**
